### ISSUE TITLE
hope to add some new function.

### ISSUE THREAD

**Issue by sdbds** [adnanc/HDT.Plugins.MetaDetector#4]
1、import top deck form http://metastats.net/classdecks/
for example，i want to import Top Warrior Archetype Decks。
2、make matchup win rate
such as this。
i find same work in another HStrack called track-o-bot
maybe it can help improve you。 
http://www.vicioussyndicate.com/vs-data-reaper-report-9/

**Comment by AdnanC** [comment]
1. I will see what I can do to make it easier to import decks into HDT.  For now you can select text and copy the deck on the site and then in HDT go to "Import -> Other -> From Clipboard Card Names". 
2. I think the VS team do a great job at breaking down the archetype match up, that's why didn't add that data right away. I will eventually add the comparison on the site as well.
